name: env-nerf
channels:
  - conda-forge
  - nvidia
  - pytorch
  - anaconda
  - defaults
dependencies:
  - pytorch-cuda
  - python=3.11.4
  - pytorch-lightning
  - torchvision
  - torchmetrics
  - ipykernel
  - matplotlib
  - numpy
